box: microsoft/aspnetcore-build
no-response-timeout: 10 
build:  
  steps:     
    - script:        
        name: restore
        cwd: DAF      
        code: |          
          dotnet restore    
    - script:        
        name: build
        cwd: DAF             
        code: |          
          dotnet build    
    - script:        
        name: publish
        cwd: DAF            
        code: |          
          dotnet publish 
