box: microsoft/aspnetcore-build
no-response-timeout: 10 
build:  
  steps:     
    - script:        
        name: restore
        cwd: DAF      
        code: |          
          dotnet restore    
    - script:        
        name: build
        cwd: DAF             
        code: |          
          dotnet build    
    - script:        
        name: publish
        cwd: DAF            
        code: |          
          dotnet publish 
deploy:
  steps:
    - internal/docker-push:
        username: $HEROKU_USER        
        password: $HEROKU_KEY 
        repository: registry.heroku.com/testnetcore21/web
        registry: https://registry.heroku.com
