box: microsoft/dotnet:2.0.0-sdk
services:
   - id: node:latest
no-response-timeout: 10 
build:  
  steps:     
    - script:        
        name: restore
        cwd: DAF      
        code: |          
          dotnet restore    
    - script:        
        name: build
        cwd: DAF             
        code: |          
          dotnet build    
    - script:        
        name: publish
        cwd: DAF            
        code: |          
          dotnet publish 
deploy:
  steps:
    - heroku-deploy:
        key: $HEROKU_KEY
        key-name: DEPLOY_KEY
        user: $HEROKU_USER
        app-name: $HEROKU_APP_NAME